<?php
/**
 * WP Super Gallery Settings Registry
 *
 * Centralizes settings metadata for defaults, admin-only visibility,
 * select options, and numeric ranges.
 *
 * @package WP_Super_Gallery
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Registry for settings metadata.
 */
class WPSG_Settings_Registry {

    /**
     * Default settings values.
     *
     * @var array
     */
    private static $defaults = [
        'auth_provider'              => 'wp-jwt',
        'api_base'                   => '',
        'theme'                      => 'default-dark',
        'allow_user_theme_override'  => true,
        'gallery_layout'             => 'grid',
        'items_per_page'             => 12,
        'enable_lightbox'            => true,
        'enable_animations'          => true,
        'video_viewport_height'      => 420,
        'image_viewport_height'      => 420,
        'thumbnail_scroll_speed'     => 1.0,
        'scroll_animation_style'     => 'smooth',
        'scroll_animation_duration_ms' => 350,
        'scroll_animation_easing'    => 'ease',
        'scroll_transition_type'     => 'slide-fade',
        'image_border_radius'        => 8,
        'video_border_radius'        => 8,
        'transition_fade_enabled'    => true,
        'video_thumbnail_width'      => 60,
        'video_thumbnail_height'     => 45,
        'image_thumbnail_width'      => 60,
        'image_thumbnail_height'     => 60,
        'thumbnail_gap'              => 6,
        'thumbnail_wheel_scroll_enabled' => true,
        'thumbnail_drag_scroll_enabled'  => true,
        'thumbnail_scroll_buttons_visible' => false,
        'nav_arrow_position'         => 'center',
        'nav_arrow_size'             => 36,
        'nav_arrow_color'            => '#ffffff',
        'nav_arrow_bg_color'         => 'rgba(0,0,0,0.45)',
        'nav_arrow_border_width'     => 0,
        'nav_arrow_hover_scale'      => 1.1,
        'nav_arrow_auto_hide_ms'     => 0,
        'dot_nav_enabled'            => true,
        'dot_nav_position'           => 'below',
        'dot_nav_size'               => 10,
        'dot_nav_active_color'       => 'var(--wpsg-color-primary)',
        'dot_nav_inactive_color'     => 'rgba(128,128,128,0.4)',
        'dot_nav_shape'              => 'circle',
        'dot_nav_spacing'            => 6,
        'dot_nav_active_scale'       => 1.3,
        'image_shadow_preset'        => 'subtle',
        'video_shadow_preset'        => 'subtle',
        'image_shadow_custom'        => '0 2px 8px rgba(0,0,0,0.15)',
        'video_shadow_custom'        => '0 2px 8px rgba(0,0,0,0.15)',
        // @deprecated Phase 24 legacy compatibility only. Persist nested gallery_config instead.
        'image_gallery_adapter_id'   => 'classic',
        'video_gallery_adapter_id'   => 'classic',
        'unified_gallery_enabled'    => false,
        'unified_gallery_adapter_id' => 'compact-grid',
        'grid_card_width'            => 160,
        'grid_card_height'           => 224,
        'mosaic_target_row_height'   => 200,
        'tile_size'                  => 150,
        'tile_gap_x'                 => 8,
        'tile_gap_y'                 => 8,
        'tile_border_width'          => 0,
        'tile_border_color'          => '#ffffff',
        'tile_glow_enabled'          => false,
        'tile_glow_color'            => '#7c9ef8',
        'tile_glow_spread'           => 12,
        'tile_hover_bounce'          => true,
        'masonry_columns'            => 0,
        'image_bg_type'              => 'none',
        'image_bg_color'             => '#1a1a2e',
        'image_bg_gradient'          => 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)',
        'image_bg_image_url'         => '',
        'video_bg_type'              => 'none',
        'video_bg_color'             => '#0d0d0d',
        'video_bg_gradient'          => 'linear-gradient(135deg, #0d0d0d 0%, #1a1a2e 100%)',
        'video_bg_image_url'         => '',
        'unified_bg_type'            => 'none',
        'unified_bg_color'           => '#1a1a2e',
        'unified_bg_gradient'        => 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)',
        'unified_bg_image_url'       => '',
        'card_border_radius'         => 8,
        'card_border_width'          => 4,
        'card_border_mode'           => 'auto',
        'card_border_color'          => '#228be6',
        'card_shadow_preset'         => 'subtle',
        'card_thumbnail_height'      => 200,
        'card_thumbnail_fit'         => 'cover',
        'card_grid_columns'          => 0,
        'card_gap_h'                 => 16,
        'card_gap_v'                 => 16,
        'card_max_width'             => 0,
        'modal_cover_height'         => 240,
        'modal_transition'           => 'pop',
        'modal_transition_duration'  => 300,
        'modal_max_height'           => 90,
        'card_display_mode'          => 'load-more',
        'card_rows_per_page'         => 3,
        'card_page_dot_nav'          => false,
        'card_page_transition_ms'    => 300,
        'show_gallery_title'         => true,
        'show_gallery_subtitle'      => true,
        'show_access_mode'           => true,
        'show_filter_tabs'           => true,
        'show_search_box'            => true,
        'app_max_width'              => 1200,
        'app_padding'                => 16,
        'wp_full_bleed_desktop'      => false,
        'wp_full_bleed_tablet'       => false,
        'wp_full_bleed_mobile'       => false,
        'image_tile_size'            => 150,
        'video_tile_size'            => 150,
        'cache_ttl'                  => 3600,
        'thumbnail_cache_ttl'        => 86400,
        'optimize_on_upload'         => false,
        'optimize_max_width'         => 1920,
        'optimize_max_height'        => 1920,
        'optimize_quality'           => 82,
        'optimize_webp_enabled'      => false,
        'advanced_settings_enabled'  => false,
        'card_locked_opacity'            => 0.5,
        'card_gradient_start_opacity'    => 0.0,
        'card_gradient_end_opacity'      => 0.85,
        'card_lock_icon_size'            => 32,
        'card_access_icon_size'          => 14,
        'card_badge_offset_y'            => 8,
        'card_company_badge_max_width'   => 160,
        'card_thumbnail_hover_transition_ms' => 300,
        'gallery_title_text'             => 'Gallery',
        'gallery_subtitle_text'          => '',
        'campaign_about_heading_text'    => 'About',
        'modal_cover_mobile_ratio'       => 0.6,
        'modal_cover_tablet_ratio'       => 0.75,
        'modal_close_button_size'        => 36,
        'modal_close_button_bg_color'    => 'rgba(0,0,0,0.5)',
        'modal_content_max_width'        => 900,
        'campaign_description_line_height' => 1.6,
        'modal_mobile_breakpoint'        => 768,
        'card_page_transition_opacity'   => 0.3,
        'upload_max_size_mb'             => 50,
        'upload_allowed_types'           => 'image/*,video/*',
        'library_page_size'              => 20,
        'media_list_page_size'           => 50,
        'media_compact_card_height'      => 100,
        'media_small_card_height'        => 80,
        'media_medium_card_height'       => 240,
        'media_large_card_height'        => 340,
        'media_list_min_width'           => 600,
        'swr_deduping_interval_ms'       => 5000,
        'notification_dismiss_ms'        => 4000,
        'tile_hover_overlay_opacity'     => 0.6,
        'tile_bounce_scale_hover'        => 1.08,
        'tile_bounce_scale_active'       => 1.02,
        'tile_bounce_duration_ms'        => 300,
        'tile_base_transition_duration_ms' => 250,
        'hex_vertical_overlap_ratio'     => 0.25,
        'diamond_vertical_overlap_ratio' => 0.45,
        'hex_clip_path'                  => 'polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)',
        'diamond_clip_path'              => 'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)',
        'tile_default_per_row'           => 5,
        'photo_normalize_height'         => 300,
        'masonry_auto_column_breakpoints' => '480:2,768:3,1024:4,1280:5',
        'grid_card_hover_shadow'         => '0 4px 12px rgba(0,0,0,0.3)',
        'grid_card_default_shadow'       => '0 2px 8px rgba(0,0,0,0.15)',
        'grid_card_hover_scale'          => 1.02,
        'tile_transition_duration_ms'    => 200,
        'lightbox_transition_ms'         => 250,
        'lightbox_backdrop_color'        => 'rgba(0,0,0,0.92)',
        'lightbox_entry_scale'           => 0.92,
        'lightbox_video_max_width'       => 900,
        'lightbox_video_height'          => 506,
        'lightbox_media_max_height'      => '85vh',
        'lightbox_z_index'               => 1000,
        'dot_nav_max_visible_dots'       => 7,
        'nav_arrow_edge_inset'           => 8,
        'nav_arrow_min_hit_target'       => 44,
        'nav_arrow_fade_duration_ms'     => 200,
        'nav_arrow_scale_transition_ms'  => 150,
        'viewport_height_mobile_ratio'   => 0.65,
        'viewport_height_tablet_ratio'   => 0.8,
        'search_input_min_width'         => 200,
        'search_input_max_width'         => 280,
        'expiry_warning_threshold_ms'    => 300000,
        'admin_search_debounce_ms'       => 300,
        'login_min_password_length'      => 1,
        'login_form_max_width'           => 400,
        'auth_bar_backdrop_blur'         => 8,
        'auth_bar_mobile_breakpoint'     => 768,
        'card_auto_columns_breakpoints'  => '480:1,768:2,1024:3,1280:4',
        'session_idle_timeout_minutes' => 0,
        // @deprecated Phase 24 legacy compatibility only. Persist nested gallery_config instead.
        'gallery_selection_mode'         => 'unified',
        'desktop_image_adapter_id'       => 'classic',
        'desktop_video_adapter_id'       => 'classic',
        'tablet_image_adapter_id'        => 'classic',
        'tablet_video_adapter_id'        => 'classic',
        'mobile_image_adapter_id'        => 'classic',
        'mobile_video_adapter_id'        => 'classic',
        'layout_builder_scope'           => 'full',
        'preserve_data_on_uninstall'     => false,
        'archive_purge_days'             => 0,
        'archive_purge_grace_days'       => 30,
        'analytics_retention_days'       => 0,
        'show_card_company_name'         => true,
        'show_card_media_counts'         => true,
        'show_card_title'                => true,
        'show_card_description'          => true,
        'show_card_border'               => true,
        'show_card_access_badge'         => true,
        'show_card_thumbnail_fade'       => true,
        'viewer_bg_type'                 => 'theme',
        'viewer_bg_color'                => '',
        'viewer_bg_gradient'             => [],
        'show_viewer_border'             => true,
        'card_max_columns'               => 0,
        'card_aspect_ratio'              => 'auto',
        'card_min_height'                => 0,
        'campaign_modal_fullscreen'      => false,
        'show_campaign_company_name'     => true,
        'show_campaign_date'             => true,
        'show_campaign_about'            => true,
        'show_campaign_description'      => true,
        'show_campaign_stats'            => true,
        'campaign_stats_admin_only'      => true,
        'campaign_open_mode'             => 'full',
        'auth_bar_display_mode'          => 'floating',
        'auth_bar_drag_margin'           => 16,
        'show_settings_tooltips'         => true,
        'typography_overrides'           => '{}',
        'show_in_context_editors'        => true,
        'show_card_info_panel'           => true,
        'show_campaign_cover_image'      => true,
        'show_campaign_tags'             => true,
        'show_campaign_admin_actions'    => true,
        'show_campaign_gallery_labels'   => true,
        'fullscreen_content_max_width'   => 0,
        'modal_max_width'                => 1200,
        'modal_bg_type'                  => 'theme',
        'modal_bg_color'                 => '',
        'modal_bg_gradient'              => '{}',
        'gallery_image_label'            => 'Images',
        'gallery_video_label'            => 'Videos',
        'gallery_label_justification'    => 'left',
        'show_gallery_label_icon'        => false,
        'modal_gallery_max_width'        => 0,
        'modal_gallery_gap'              => 32,
        'modal_gallery_margin'           => 0,
        'modal_gallery_vertical_align'   => 'start',
        'modal_gallery_offset_y'         => 0,
        'gallery_sizing_mode'            => 'auto',
        'gallery_manual_height'          => '420px',
        'gallery_section_max_width'      => 0,
        'gallery_section_max_height'     => 0,
        'gallery_section_height_mode'    => 'auto',
        'gallery_section_min_width'      => 300,
        'gallery_section_min_height'     => 150,
        'gallery_section_content_align_x' => 'center',
        'gallery_section_content_align_y' => 'start',
        'gallery_section_content_offset_x' => 0,
        'gallery_section_content_offset_y' => 0,
        'section_scale'                  => 1,
        'per_type_section_equal_height'  => false,
        'modal_inner_padding'            => 16,
        'gallery_section_padding'        => 16,
        'adapter_content_padding'        => 0,
        'adapter_sizing_mode'            => 'fill',
        'adapter_max_width_pct'          => 100,
        'adapter_max_height_pct'         => 100,
        'card_max_width_unit'            => 'px',
        'card_justify_content'           => 'center',
        'card_scale'                     => 1,
        'card_gallery_vertical_align'    => 'start',
        'card_gallery_min_height'        => 0,
        'card_gallery_max_height'        => 0,
        'card_gallery_offset_x'          => 0,
        'card_gallery_offset_y'          => 0,
        'adapter_item_gap'               => 16,
        'adapter_justify_content'        => 'center',
        'item_scale'                     => 1,
        'modal_content_vertical_align'   => 'top',
        'carousel_visible_cards'         => 1,
        'carousel_autoplay'              => false,
        'carousel_autoplay_speed'        => 3000,
        'carousel_autoplay_pause_on_hover' => true,
        'carousel_autoplay_direction'    => 'ltr',
        'carousel_drag_enabled'          => true,
        'carousel_darken_unfocused'      => false,
        'carousel_darken_opacity'        => 0.5,
        'carousel_edge_fade'             => false,
        'carousel_loop'                  => true,
        'carousel_gap'                   => 16,
        'settings_drawer_blur_enabled'   => true,
    ];

    /**
     * Settings that are admin-only.
     *
     * @var string[]
     */
    private static $admin_only_fields = [
        'auth_provider',
        'api_base',
        'allow_user_theme_override',
        'cache_ttl',
        'thumbnail_cache_ttl',
        'optimize_on_upload',
        'optimize_max_width',
        'optimize_max_height',
        'optimize_quality',
        'optimize_webp_enabled',
        'advanced_settings_enabled',
        'upload_max_size_mb',
        'upload_allowed_types',
        'swr_deduping_interval_ms',
        'notification_dismiss_ms',
        'expiry_warning_threshold_ms',
        'admin_search_debounce_ms',
        'login_min_password_length',
        'login_form_max_width',
        'auth_bar_backdrop_blur',
        'auth_bar_mobile_breakpoint',
        'session_idle_timeout_minutes',
        'preserve_data_on_uninstall',
        'archive_purge_days',
        'archive_purge_grace_days',
        'analytics_retention_days',
    ];

    /**
     * Valid options for select fields.
     *
     * @var array
     */
    private static $valid_options = [
        'auth_provider'  => ['wp-jwt', 'none'],
        'theme'          => [
            'default-dark',
            'default-light',
            'material-dark',
            'material-light',
            'darcula',
            'nord',
            'solarized-dark',
            'solarized-light',
            'high-contrast',
            'catppuccin-mocha',
            'tokyo-night',
            'gruvbox-dark',
            'cyberpunk',
            'synthwave',
            'github-light',
            'catppuccin-latte',
        ],
        'gallery_layout' => ['grid', 'masonry', 'carousel'],
        'scroll_animation_style' => ['smooth', 'instant'],
        'scroll_animation_easing' => ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'],
        'scroll_transition_type' => ['fade', 'slide', 'slide-fade'],
        'nav_arrow_position'     => ['top', 'center', 'bottom'],
        'dot_nav_position'       => ['below', 'overlay-bottom', 'overlay-top'],
        'dot_nav_shape'          => ['circle', 'pill', 'square'],
        'image_shadow_preset'    => ['none', 'subtle', 'medium', 'strong', 'custom'],
        'video_shadow_preset'    => ['none', 'subtle', 'medium', 'strong', 'custom'],
        'card_shadow_preset'     => ['none', 'subtle', 'medium', 'dramatic'],
        'card_thumbnail_fit'     => ['cover', 'contain'],
        'card_border_mode'       => ['auto', 'single', 'individual'],
        'modal_transition'       => ['pop', 'fade', 'slide-up'],
        'card_display_mode'      => ['show-all', 'load-more', 'paginated'],
        'image_bg_type'          => ['none', 'solid', 'gradient', 'image'],
        'video_bg_type'          => ['none', 'solid', 'gradient', 'image'],
        'unified_bg_type'        => ['none', 'solid', 'gradient', 'image'],
        // @deprecated Phase 24 legacy compatibility only. Persist nested gallery_config instead.
        'image_gallery_adapter_id'   => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond'],
        'video_gallery_adapter_id'   => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond'],
        'unified_gallery_adapter_id' => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond'],
        // @deprecated Phase 24 legacy compatibility only. Persist nested gallery_config instead.
        'gallery_selection_mode'     => ['unified', 'per-breakpoint'],
        'desktop_image_adapter_id'   => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond', 'layout-builder'],
        'desktop_video_adapter_id'   => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond', 'layout-builder'],
        'tablet_image_adapter_id'    => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond', 'layout-builder'],
        'tablet_video_adapter_id'    => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond', 'layout-builder'],
        'mobile_image_adapter_id'    => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond', 'layout-builder'],
        'mobile_video_adapter_id'    => ['classic', 'compact-grid', 'mosaic', 'justified', 'masonry', 'hexagonal', 'circular', 'diamond', 'layout-builder'],
        'layout_builder_scope'       => ['full', 'viewport'],
        'viewer_bg_type'             => ['theme', 'transparent', 'solid', 'gradient'],
        'modal_bg_type'              => ['theme', 'transparent', 'solid', 'gradient'],
        'card_aspect_ratio'          => ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9'],
        'gallery_label_justification' => ['left', 'center', 'right'],
        'campaign_open_mode'          => ['full', 'galleries-only'],
        'auth_bar_display_mode'       => ['bar', 'floating', 'draggable', 'minimal', 'auto-hide'],
        'gallery_sizing_mode'         => ['auto', 'viewport', 'manual'],
        'gallery_section_height_mode' => ['auto', 'manual', 'viewport'],
        'adapter_sizing_mode'         => ['fill', 'manual'],
        'card_max_width_unit'         => ['px', '%'],
        'card_justify_content'        => ['start', 'center', 'end', 'space-between', 'space-evenly'],
        'card_gallery_vertical_align' => ['start', 'center', 'end'],
        'adapter_justify_content'     => ['start', 'center', 'end', 'space-between', 'space-evenly', 'stretch'],
        'modal_content_vertical_align' => ['top', 'center', 'bottom'],
        'modal_gallery_vertical_align' => ['start', 'center', 'end'],
        'gallery_section_content_align_x' => ['start', 'center', 'end'],
        'gallery_section_content_align_y' => ['start', 'center', 'end'],
        'carousel_autoplay_direction'  => ['ltr', 'rtl'],
    ];

    /**
     * Numeric ranges for settings.
     *
     * @var array<string, array{0: int|float, 1: int|float}>
     */
    private static $field_ranges = [
        'items_per_page'              => [1, 100],
        'video_viewport_height'       => [180, 900],
        'image_viewport_height'       => [180, 900],
        'thumbnail_scroll_speed'      => [0.25, 3],
        'scroll_animation_duration_ms' => [0, 2000],
        'image_border_radius'         => [0, 48],
        'video_border_radius'         => [0, 48],
        'video_thumbnail_width'       => [30, 200],
        'video_thumbnail_height'      => [30, 200],
        'image_thumbnail_width'       => [30, 200],
        'image_thumbnail_height'      => [30, 200],
        'thumbnail_gap'               => [0, 24],
        'nav_arrow_size'              => [20, 64],
        'nav_arrow_border_width'      => [0, 6],
        'nav_arrow_hover_scale'       => [1.0, 1.5],
        'nav_arrow_auto_hide_ms'      => [0, 10000],
        'dot_nav_size'                => [4, 24],
        'dot_nav_spacing'             => [2, 20],
        'dot_nav_active_scale'        => [1.0, 2.0],
        'mosaic_target_row_height'    => [60, 600],
        'grid_card_width'             => [80, 400],
        'grid_card_height'            => [80, 600],
        'tile_size'                   => [60, 400],
        'tile_gap_x'                  => [0, 60],
        'tile_gap_y'                  => [0, 60],
        'tile_border_width'           => [0, 20],
        'tile_glow_spread'            => [2, 60],
        'masonry_columns'             => [0, 8],
        'card_border_radius'          => [0, 24],
        'card_border_width'           => [0, 8],
        'card_thumbnail_height'       => [100, 400],
        'card_grid_columns'           => [0, 6],
        'card_gap_h'                  => [0, 48],
        'card_gap_v'                  => [0, 48],
        'card_gallery_min_height'     => [0, 1200],
        'card_gallery_max_height'     => [0, 2000],
        'card_gallery_offset_x'       => [-200, 200],
        'card_gallery_offset_y'       => [-200, 200],
        'modal_cover_height'          => [100, 400],
        'modal_transition_duration'   => [100, 1000],
        'modal_max_height'            => [50, 100],
        'card_rows_per_page'          => [1, 10],
        'card_page_transition_ms'     => [100, 800],
        'app_max_width'               => [0, 3000],
        'app_padding'                 => [0, 100],
        'image_tile_size'             => [60, 400],
        'video_tile_size'             => [60, 400],
        'cache_ttl'                   => [0, 604800],
        'thumbnail_cache_ttl'         => [0, 604800],
        'optimize_max_width'          => [100, 4096],
        'optimize_max_height'         => [100, 4096],
        'optimize_quality'            => [10, 100],
        'card_locked_opacity'         => [0, 1],
        'card_gradient_start_opacity' => [0, 1],
        'card_gradient_end_opacity'   => [0, 1],
        'card_lock_icon_size'         => [12, 64],
        'card_access_icon_size'       => [8, 32],
        'card_badge_offset_y'         => [0, 32],
        'card_company_badge_max_width' => [60, 400],
        'card_thumbnail_hover_transition_ms' => [0, 1000],
        'modal_cover_mobile_ratio'    => [0.2, 1],
        'modal_cover_tablet_ratio'    => [0.2, 1],
        'modal_close_button_size'     => [20, 64],
        'modal_content_max_width'     => [400, 2000],
        'campaign_description_line_height' => [1.0, 3.0],
        'modal_mobile_breakpoint'     => [320, 1280],
        'card_page_transition_opacity' => [0, 1],
        'upload_max_size_mb'          => [1, 500],
        'library_page_size'           => [5, 100],
        'media_list_page_size'        => [10, 200],
        'media_compact_card_height'   => [40, 300],
        'media_small_card_height'     => [40, 300],
        'media_medium_card_height'    => [100, 600],
        'media_large_card_height'     => [100, 800],
        'media_list_min_width'        => [200, 1200],
        'swr_deduping_interval_ms'    => [0, 60000],
        'notification_dismiss_ms'     => [1000, 30000],
        'tile_hover_overlay_opacity'  => [0, 1],
        'tile_bounce_scale_hover'     => [1.0, 1.5],
        'tile_bounce_scale_active'    => [0.8, 1.2],
        'tile_bounce_duration_ms'     => [0, 1000],
        'tile_base_transition_duration_ms' => [0, 1000],
        'hex_vertical_overlap_ratio'  => [0, 0.5],
        'diamond_vertical_overlap_ratio' => [0, 0.8],
        'tile_default_per_row'        => [1, 12],
        'photo_normalize_height'      => [100, 800],
        'grid_card_hover_scale'       => [1.0, 1.3],
        'tile_transition_duration_ms' => [0, 1000],
        'lightbox_transition_ms'      => [0, 1000],
        'lightbox_entry_scale'        => [0.5, 1.0],
        'lightbox_video_max_width'    => [300, 2000],
        'lightbox_video_height'       => [200, 1200],
        'lightbox_z_index'            => [1, 100000],
        'dot_nav_max_visible_dots'    => [3, 20],
        'nav_arrow_edge_inset'        => [0, 48],
        'nav_arrow_min_hit_target'    => [24, 80],
        'nav_arrow_fade_duration_ms'  => [0, 1000],
        'nav_arrow_scale_transition_ms' => [0, 1000],
        'viewport_height_mobile_ratio' => [0.3, 1.0],
        'viewport_height_tablet_ratio' => [0.3, 1.0],
        'search_input_min_width'      => [100, 600],
        'search_input_max_width'      => [100, 800],
        'expiry_warning_threshold_ms' => [60000, 3600000],
        'admin_search_debounce_ms'    => [50, 2000],
        'login_min_password_length'   => [1, 32],
        'login_form_max_width'        => [200, 800],
        'auth_bar_backdrop_blur'      => [0, 24],
        'auth_bar_mobile_breakpoint'  => [320, 1280],
        'session_idle_timeout_minutes' => [0, 480],
        'archive_purge_days'           => [0, 365],
        'archive_purge_grace_days'     => [7, 90],
        'analytics_retention_days'     => [0, 730],
        'card_max_columns'             => [0, 8],
        'card_min_height'              => [0, 600],
        'auth_bar_drag_margin'         => [0, 64],
        'fullscreen_content_max_width' => [0, 3000],
        'modal_max_width'              => [0, 3000],
        'modal_gallery_max_width'      => [0, 3000],
        'modal_gallery_gap'            => [0, 120],
        'modal_gallery_margin'         => [0, 120],
        'modal_gallery_offset_y'       => [-200, 200],
        'gallery_section_max_width'    => [0, 3000],
        'gallery_section_max_height'   => [0, 3000],
        'gallery_section_min_width'    => [0, 1200],
        'gallery_section_min_height'   => [0, 1200],
        'gallery_section_content_offset_x' => [-200, 200],
        'gallery_section_content_offset_y' => [-200, 200],
        'modal_inner_padding'          => [0, 64],
        'gallery_section_padding'      => [0, 60],
        'adapter_content_padding'      => [0, 48],
        'adapter_max_width_pct'        => [50, 100],
        'adapter_max_height_pct'       => [50, 100],
        'adapter_item_gap'             => [0, 64],
        'card_scale'                   => [0.5, 2.0],
        'section_scale'                => [0.5, 2.0],
        'item_scale'                   => [0.5, 2.0],
        'carousel_visible_cards'       => [1, 10],
        'carousel_autoplay_speed'      => [500, 15000],
        'carousel_darken_opacity'      => [0, 1],
        'carousel_gap'                 => [0, 64],
    ];

    private static function create_default_gallery_scope_config($adapter_id) {
        return [
            'adapterId' => $adapter_id,
        ];
    }

    private static function create_default_gallery_config() {
        return [
            'mode' => 'per-type',
            'breakpoints' => [
                'desktop' => [
                    'unified' => self::create_default_gallery_scope_config('compact-grid'),
                    'image' => self::create_default_gallery_scope_config('classic'),
                    'video' => self::create_default_gallery_scope_config('classic'),
                ],
                'tablet' => [
                    'unified' => self::create_default_gallery_scope_config('compact-grid'),
                    'image' => self::create_default_gallery_scope_config('classic'),
                    'video' => self::create_default_gallery_scope_config('classic'),
                ],
                'mobile' => [
                    'unified' => self::create_default_gallery_scope_config('compact-grid'),
                    'image' => self::create_default_gallery_scope_config('classic'),
                    'video' => self::create_default_gallery_scope_config('classic'),
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public static function get_defaults() {
        $defaults = self::$defaults;

        if (!array_key_exists('gallery_config', $defaults)) {
            $defaults['gallery_config'] = self::create_default_gallery_config();
        }

        return $defaults;
    }

    /**
     * @return string[]
     */
    public static function get_admin_only_fields() {
        return self::$admin_only_fields;
    }

    /**
     * @return array
     */
    public static function get_valid_options() {
        return self::$valid_options;
    }

    /**
     * @return array<string, array{0: int|float, 1: int|float}>
     */
    public static function get_field_ranges() {
        return self::$field_ranges;
    }
}