<?php

if (!defined('ABSPATH')) {
    exit;
}

class WPSG_CPT {
    const POST_TYPE = 'wpsg_campaign';

    /**
     * Custom CPT capabilities generated by capability_type.
     * Primitive (plural) caps that must be granted to roles.
     */
    const CPT_CAPS = [
        'edit_wpsg_campaigns',
        'edit_others_wpsg_campaigns',
        'publish_wpsg_campaigns',
        'read_private_wpsg_campaigns',
        'delete_wpsg_campaigns',
        'delete_private_wpsg_campaigns',
        'delete_published_wpsg_campaigns',
        'delete_others_wpsg_campaigns',
        'edit_private_wpsg_campaigns',
        'edit_published_wpsg_campaigns',
    ];

    /**
     * Canonical list of valid gallery adapter identifiers.
     * Used by both global settings and per-campaign overrides.
     */
    const VALID_ADAPTERS = [
        'classic',
        'compact-grid',
        'mosaic',
        'justified',
        'masonry',
        'hexagonal',
        'circular',
        'diamond',
        'layout-builder',
        'spotlight',      // P31-E: Spotlight / Hero adapter
        'scroll-snap',    // P31-F: Vertical Scroll Snap adapter
        'coverflow',      // P48-G: Coverflow / 3D adapter (backfilled in P50-C)
        'pinterest',      // P48: Pinterest mosaic adapter (backfilled in P50-C)
        'stacked',        // P50-C: Stacked / Deck adapter
        'isotope',        // P50-D: Isotope / Filterable Grid adapter
    ];

    public static function register() {
        // P47-I: Space column + filter in WP admin campaign list.
        // P47-J: Inline "Create Space" form + handler.
        if (is_admin()) {
            add_filter('manage_wpsg_campaign_posts_columns', [self::class, 'add_space_column']);
            add_action('manage_wpsg_campaign_posts_custom_column', [self::class, 'render_space_column'], 10, 2);
            add_action('restrict_manage_posts', [self::class, 'render_space_filter_dropdown']);
            add_action('pre_get_posts', [self::class, 'apply_space_filter']);
            add_action('manage_posts_extra_tablenav', [self::class, 'render_create_space_ui']);
            add_action('admin_post_wpsg_create_space', [self::class, 'handle_create_space']);
            // P51-G: clarify the ambiguous default "Count" column on the Companies
            // term list — it counts associated campaigns.
            add_filter('manage_edit-wpsg_company_columns', [self::class, 'rename_company_count_column']);
        }

        register_post_type(self::POST_TYPE, [
            // P51-G: rename the top-level WP menu to "SuperGallery" (menu_name)
            // while keeping the campaign list item labelled "Campaigns" (all_items).
            'label' => __('Campaigns', 'wp-super-gallery'),
            'labels' => [
                'name'               => __('Campaigns', 'wp-super-gallery'),
                'singular_name'      => __('Campaign', 'wp-super-gallery'),
                'menu_name'          => __('SuperGallery', 'wp-super-gallery'),
                'all_items'          => __('Campaigns', 'wp-super-gallery'),
                'add_new'            => __('Add New', 'wp-super-gallery'),
                'add_new_item'       => __('Add New Campaign', 'wp-super-gallery'),
                'edit_item'          => __('Edit Campaign', 'wp-super-gallery'),
                'new_item'           => __('New Campaign', 'wp-super-gallery'),
                'view_item'          => __('View Campaign', 'wp-super-gallery'),
                'view_items'         => __('View Campaigns', 'wp-super-gallery'),
                'search_items'       => __('Search Campaigns', 'wp-super-gallery'),
                'not_found'          => __('No campaigns found', 'wp-super-gallery'),
                'not_found_in_trash' => __('No campaigns found in Trash', 'wp-super-gallery'),
            ],
            'public' => false,
            'show_ui' => true,
            'show_in_rest' => true,
            'supports' => ['title', 'editor', 'thumbnail'],
            'menu_icon' => 'dashicons-images-alt2',
            'capability_type' => ['wpsg_campaign', 'wpsg_campaigns'],
            'map_meta_cap' => true,
        ]);

        register_taxonomy('wpsg_company', self::POST_TYPE, [
            // P51-G: explicit non-hierarchical labels. Without these WP falls back
            // to the default tag strings ("Add New Tag", "Separate tags with commas").
            'label' => __('Companies', 'wp-super-gallery'),
            'labels' => [
                'name'                       => __('Companies', 'wp-super-gallery'),
                'singular_name'              => __('Company', 'wp-super-gallery'),
                'menu_name'                  => __('Companies', 'wp-super-gallery'),
                'all_items'                  => __('All Companies', 'wp-super-gallery'),
                'edit_item'                  => __('Edit Company', 'wp-super-gallery'),
                'view_item'                  => __('View Company', 'wp-super-gallery'),
                'update_item'                => __('Update Company', 'wp-super-gallery'),
                'add_new_item'               => __('Add New Company', 'wp-super-gallery'),
                'new_item_name'              => __('New Company Name', 'wp-super-gallery'),
                'search_items'               => __('Search Companies', 'wp-super-gallery'),
                'popular_items'              => __('Popular Companies', 'wp-super-gallery'),
                'not_found'                  => __('No companies found', 'wp-super-gallery'),
                'back_to_items'              => __('← Back to Companies', 'wp-super-gallery'),
                'separate_items_with_commas' => __('Separate companies with commas', 'wp-super-gallery'),
                'add_or_remove_items'        => __('Add or remove companies', 'wp-super-gallery'),
                'choose_from_most_used'      => __('Choose from the most used companies', 'wp-super-gallery'),
            ],
            'public' => false,
            'show_ui' => true,
            'show_in_rest' => true,
            'hierarchical' => false,
        ]);

        // P14-G: Campaign tags (non-hierarchical, like WordPress post tags).
        register_taxonomy('wpsg_campaign_tag', self::POST_TYPE, [
            'label' => __('Campaign Tags', 'wp-super-gallery'),
            'public' => false,
            'show_ui' => true,
            'show_in_rest' => true,
            'hierarchical' => false,
            'show_admin_column' => true,
        ]);

        // P18-H: Campaign categories (flat, organisational grouping).
        register_taxonomy('wpsg_campaign_category', self::POST_TYPE, [
            'label'             => __('Campaign Categories', 'wp-super-gallery'),
            'public'            => false,
            'show_ui'           => true,
            'show_in_rest'      => true,
            'rest_base'         => 'campaign-categories',
            'hierarchical'      => true,
            'show_admin_column' => true,
        ]);

        // P14-G: Media tags (attached to attachments for cross-campaign organization).
        register_taxonomy('wpsg_media_tag', 'attachment', [
            'label' => __('Media Tags', 'wp-super-gallery'),
            'public' => false,
            'show_ui' => true,
            'show_in_rest' => true,
            'hierarchical' => false,
        ]);

        // P20-I-1: Layout templates CPT (replaces wp_options storage).
        register_post_type('wpsg_layout_tpl', [
            'label' => __('Layout Templates', 'wp-super-gallery'),
            'public' => false,
            'show_ui' => false,
            'show_in_rest' => false,
            'supports' => ['title'],
            'capability_type' => ['wpsg_campaign', 'wpsg_campaigns'],
            'map_meta_cap' => true,
        ]);

        register_post_meta(self::POST_TYPE, 'visibility', [
            'type' => 'string',
            'single' => true,
            'show_in_rest' => true,
            'default' => 'private',
            'sanitize_callback' => [ self::class, 'sanitize_visibility' ],
        ]);

        register_post_meta(self::POST_TYPE, 'status', [
            'type' => 'string',
            'single' => true,
            'show_in_rest' => true,
            'default' => 'draft',
            'sanitize_callback' => [ self::class, 'sanitize_status' ],
        ]);

        register_post_meta(self::POST_TYPE, 'media_items', [
            'type' => 'array',
            'single' => true,
            'show_in_rest' => [
                'schema' => [
                    'type'  => 'array',
                    'items' => [
                        'type'       => 'object',
                        'properties' => [
                            'id'           => ['type' => 'string'],
                            'type'         => ['type' => 'string'],
                            'source'       => ['type' => 'string'],
                            'url'          => ['type' => 'string'],
                            'thumbnail'    => ['type' => 'string'],
                            'caption'      => ['type' => 'string'],
                            'order'        => ['type' => 'integer'],
                            'embedUrl'     => ['type' => 'string'],
                            'provider'     => ['type' => 'string'],
                            'attachmentId' => ['type' => 'integer'],
                            'title'        => ['type' => 'string'],
                        ],
                    ],
                ],
            ],
            'default' => [],
            'sanitize_callback' => [ self::class, 'sanitize_media_items' ],
        ]);

        register_post_meta(self::POST_TYPE, 'tags', [
            'type' => 'array',
            'single' => true,
            'show_in_rest' => [
                'schema' => [
                    'type'  => 'array',
                    'items' => ['type' => 'string'],
                ],
            ],
            'default' => [],
            'sanitize_callback' => [ self::class, 'sanitize_tags' ],
        ]);

        register_post_meta(self::POST_TYPE, 'cover_image', [
            'type' => 'string',
            'single' => true,
            'show_in_rest' => true,
            'default' => '',
            'sanitize_callback' => 'esc_url_raw',
        ]);

        register_post_meta(self::POST_TYPE, 'access_grants', [
            'type' => 'array',
            'single' => true,
            'show_in_rest' => false,
            'default' => [],
        ]);

        register_post_meta(self::POST_TYPE, 'access_overrides', [
            'type' => 'array',
            'single' => true,
            'show_in_rest' => false,
            'default' => [],
        ]);

        // P13-D: Campaign scheduling — optional ISO 8601 date strings.
        // null/empty = no schedule constraint.
        register_post_meta(self::POST_TYPE, 'publish_at', [
            'type' => 'string',
            'single' => true,
            'show_in_rest' => true,
            'default' => '',
            'sanitize_callback' => [ self::class, 'sanitize_datetime' ],
        ]);

        register_post_meta(self::POST_TYPE, 'unpublish_at', [
            'type' => 'string',
            'single' => true,
            'show_in_rest' => true,
            'default' => '',
            'sanitize_callback' => [ self::class, 'sanitize_datetime' ],
        ]);

        register_term_meta('wpsg_company', 'access_grants', [
            'type' => 'array',
            'single' => true,
            'show_in_rest' => false,
            'default' => [],
        ]);

        // P47-A: Space assignment.
        register_post_meta('wpsg_campaign', '_wpsg_space_id', [
            'type'         => 'integer',
            'single'       => true,
            'show_in_rest' => false,
            'default'      => 0,
        ]);
        register_term_meta('wpsg_company', '_wpsg_space_id', [
            'type'         => 'integer',
            'single'       => true,
            'show_in_rest' => false,
            'default'      => 0,
        ]);
    }

    // ── Sanitize callbacks (P20-D) ───────────────────────────

    /**
     * Whitelist visibility values.
     *
     * @since 0.18.0 P20-D
     * @param  mixed $value Raw value.
     * @return string Sanitized value.
     */
    public static function sanitize_visibility( $value ): string {
        return in_array( $value, [ 'public', 'private' ], true ) ? $value : 'private';
    }

    /**
     * Whitelist status values.
     *
     * @since 0.18.0 P20-D
     * @param  mixed $value Raw value.
     * @return string Sanitized value.
     */
    public static function sanitize_status( $value ): string {
        return in_array( $value, [ 'draft', 'active', 'archived' ], true ) ? $value : 'draft';
    }

    /**
     * Sanitize media_items array.
     *
     * Validates structure and sanitizes each field. Malformed entries are
     * silently dropped.
     *
     * @since 0.18.0 P20-D
     * @param  mixed $value Raw value.
     * @return array Sanitized media items.
     */
    public static function sanitize_media_items( $value ): array {
        if ( ! is_array( $value ) ) {
            return [];
        }

        $valid_types    = [ 'image', 'video', 'embed' ];
        // 'upload' and 'library' were added in later phases but the allowlist was
        // never extended; all five values are used by the REST API and the frontend.
        $valid_sources  = [ 'upload', 'library', 'wp', 'external', 'oembed' ];
        $sanitized      = [];

        foreach ( $value as $item ) {
            if ( ! is_array( $item ) ) {
                continue;
            }

            $clean = [
                'id'           => isset( $item['id'] ) ? sanitize_text_field( $item['id'] ) : '',
                'type'         => isset( $item['type'] ) && in_array( $item['type'], $valid_types, true )
                    ? $item['type'] : 'image',
                'source'       => isset( $item['source'] ) && in_array( $item['source'], $valid_sources, true )
                    ? $item['source'] : 'wp',
                'url'          => isset( $item['url'] ) ? esc_url_raw( $item['url'] ) : '',
                'thumbnail'    => isset( $item['thumbnail'] ) ? esc_url_raw( $item['thumbnail'] ) : '',
                'caption'      => isset( $item['caption'] ) ? sanitize_text_field( $item['caption'] ) : '',
                'order'        => isset( $item['order'] ) ? intval( $item['order'] ) : 0,
                'embedUrl'     => isset( $item['embedUrl'] ) ? esc_url_raw( $item['embedUrl'] ) : '',
                'provider'     => isset( $item['provider'] ) ? sanitize_text_field( $item['provider'] ) : '',
                'attachmentId' => isset( $item['attachmentId'] ) ? intval( $item['attachmentId'] ) : 0,
                'title'        => isset( $item['title'] ) ? sanitize_text_field( $item['title'] ) : '',
            ];

            // Drop entries with no usable ID
            if ( $clean['id'] !== '' ) {
                $sanitized[] = $clean;
            }
        }

        return $sanitized;
    }

    /**
     * Sanitize tags array.
     *
     * @since 0.18.0 P20-D
     * @param  mixed $value Raw value.
     * @return array Sanitized tag strings.
     */
    public static function sanitize_tags( $value ): array {
        if ( ! is_array( $value ) ) {
            return [];
        }
        return array_values( array_filter( array_map( 'sanitize_text_field', $value ) ) );
    }

    /**
     * Validate and sanitize ISO 8601 datetime strings.
     *
     * Accepts ISO 8601 inputs and the plugin's stored UTC format.
     * All valid inputs are normalized to Y-m-d H:i:s in UTC for storage.
     *
     * @since 0.18.0 P20-D
     * @param  mixed $value Raw value.
     * @return string Normalized UTC datetime or empty string.
     */
    public static function sanitize_datetime( $value ): string {
        if ( ! is_string( $value ) || trim( $value ) === '' ) {
            return '';
        }
        $value = sanitize_text_field( $value );

        $formats = array( 'Y-m-d H:i:s', 'Y-m-d\TH:i:sP', 'Y-m-d\TH:i:s\Z', 'Y-m-d\TH:i:s' );
        foreach ( $formats as $fmt ) {
            $dt = \DateTimeImmutable::createFromFormat( '!' . $fmt, $value, new \DateTimeZone( 'UTC' ) );
            $errors = \DateTimeImmutable::getLastErrors();
            $has_errors = is_array( $errors )
                ? ( $errors['warning_count'] > 0 || $errors['error_count'] > 0 )
                : false;

            if ( $dt && ! $has_errors && $dt->format( $fmt ) === $value ) {
                return $dt->setTimezone( new \DateTimeZone( 'UTC' ) )->format( 'Y-m-d H:i:s' );
            }
        }
        return '';
    }

    // ── P51-G: Companies term-list column relabel ─────────────────────────────

    /**
     * Rename the default "Count" column on the Companies term list to
     * "Campaigns", since the count reflects associated campaigns.
     *
     * @param array $columns Term-list columns.
     * @return array
     */
    public static function rename_company_count_column(array $columns): array {
        if (isset($columns['posts'])) {
            $columns['posts'] = __('Campaigns', 'wp-super-gallery');
        }
        return $columns;
    }

    // ── P47-I: Space column + filter ──────────────────────────────────────────

    public static function add_space_column(array $columns): array {
        $new = [];
        foreach ($columns as $key => $label) {
            $new[$key] = $label;
            if ($key === 'title') {
                $new['wpsg_space'] = __('Space', 'wp-super-gallery');
            }
        }
        return $new;
    }

    public static function render_space_column(string $column, int $post_id): void {
        if ($column !== 'wpsg_space') {
            return;
        }
        $space_id = (int) get_post_meta($post_id, '_wpsg_space_id', true);
        if ($space_id <= 0) {
            echo '&mdash;';
            return;
        }
        $space = class_exists('WPSG_DB') ? WPSG_DB::get_space($space_id) : null;
        echo $space ? esc_html($space->name) : esc_html("Space #{$space_id}");
    }

    public static function render_space_filter_dropdown(string $post_type): void {
        if ($post_type !== self::POST_TYPE) {
            return;
        }
        global $wpdb;
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery
        $spaces = $wpdb->get_results(
            "SELECT id, name FROM {$wpdb->prefix}wpsg_spaces WHERE archived = 0 ORDER BY name ASC"
        );
        if (empty($spaces)) {
            return;
        }
        $selected = isset($_GET['wpsg_space_filter']) ? intval($_GET['wpsg_space_filter']) : 0;  // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Admin list-table filter: read-only GET navigation (intval'd), core-idiomatic, no nonce.
        echo '<select name="wpsg_space_filter">';
        echo '<option value="">' . esc_html__('All spaces', 'wp-super-gallery') . '</option>';
        foreach ($spaces as $s) {
            printf(
                '<option value="%d"%s>%s</option>',
                (int) $s->id,
                selected($selected, (int) $s->id, false),
                esc_html($s->name)
            );
        }
        echo '</select>';
    }

    public static function apply_space_filter(\WP_Query $query): void {
        if (!is_admin() || !$query->is_main_query()) {
            return;
        }
        if ($query->get('post_type') !== self::POST_TYPE) {
            return;
        }
        $space_id = isset($_GET['wpsg_space_filter']) ? intval($_GET['wpsg_space_filter']) : 0;  // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Admin list-table filter: read-only GET navigation (intval'd), core-idiomatic, no nonce.
        if ($space_id <= 0) {
            return;
        }
        $meta = $query->get('meta_query') ?: [];
        $meta[] = ['key' => '_wpsg_space_id', 'value' => $space_id, 'type' => 'NUMERIC'];
        $query->set('meta_query', $meta);
    }

    // ── P47-J: Inline space creation from Campaigns list ─────────────────────

    public static function render_create_space_ui(string $which): void {
        global $typenow;
        if ($typenow !== self::POST_TYPE || $which !== 'top') {
            return;
        }
        ?>
        <div class="wpsg-create-space" style="display:inline-block;margin-left:4px;vertical-align:middle;">
            <details>
                <summary class="button" style="cursor:pointer;"><?php esc_html_e('+ New Space', 'wp-super-gallery'); ?></summary>
                <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"
                      style="margin-top:6px;padding:8px 10px;background:#f6f7f7;border:1px solid #ddd;border-radius:3px;">
                    <input type="hidden" name="action" value="wpsg_create_space">
                    <?php wp_nonce_field('wpsg_create_space', '_wpsg_nonce'); ?>
                    <input type="text" name="wpsg_space_name" placeholder="<?php esc_attr_e('Space name', 'wp-super-gallery'); ?>"
                           required style="margin-right:4px;vertical-align:middle;">
                    <input type="text" name="wpsg_space_slug" placeholder="<?php esc_attr_e('Slug (auto)', 'wp-super-gallery'); ?>"
                           style="margin-right:4px;vertical-align:middle;">
                    <button type="submit" class="button button-primary"><?php esc_html_e('Create', 'wp-super-gallery'); ?></button>
                </form>
            </details>
        </div>
        <?php
    }

    public static function handle_create_space(): void {
        // P52-A3: creating spaces is a System Admin action (manage_options).
        if (!current_user_can('manage_options') || !check_admin_referer('wpsg_create_space', '_wpsg_nonce')) {
            wp_die(esc_html__('Forbidden', 'wp-super-gallery'));
        }
        $name     = sanitize_text_field(wp_unslash($_POST['wpsg_space_name'] ?? ''));
        $raw_slug = sanitize_text_field(wp_unslash($_POST['wpsg_space_slug'] ?? ''));
        $slug     = sanitize_title($raw_slug ?: $name);
        $redirect = admin_url('edit.php?post_type=' . self::POST_TYPE);
        if (empty($name) || empty($slug)) {
            wp_safe_redirect(add_query_arg('wpsg_error', '1', $redirect));
            exit;
        }
        if (!class_exists('WPSG_DB')) {
            wp_safe_redirect(add_query_arg('wpsg_error', '1', $redirect));
            exit;
        }
        $new_id = WPSG_DB::insert_space(['name' => $name, 'slug' => $slug]);
        if (!$new_id) {
            wp_safe_redirect(add_query_arg('wpsg_error', '1', $redirect));
            exit;
        }
        WPSG_REST_Base::bump_cache_version();
        wp_safe_redirect(add_query_arg('wpsg_space_created', rawurlencode($name), $redirect));
        exit;
    }
}
