<?php
/**
 * WP Super Gallery Settings Registry
 *
 * Centralizes settings metadata for defaults, admin-only visibility,
 * select options, and numeric ranges.
 *
 * @package WP_Super_Gallery
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Registry for settings metadata.
 */
class WPSG_Settings_Registry {

    /**
     * Default settings values.
     *
     * @var array
     */
    private static $defaults = [
        'auth_provider'              => 'wp-jwt',
        'api_base'                   => '',
        'theme'                      => 'default-dark',
        'allow_user_theme_override'  => true,
        'debug_component_markers'    => false,
        'gallery_layout'             => 'grid',
        'items_per_page'             => 12,
        'enable_lightbox'            => true,
        'enable_animations'          => true,
        'video_viewport_height'      => 420,
        'image_viewport_height'      => 420,
        'thumbnail_scroll_speed'     => 1.0,
        'scroll_animation_style'     => 'smooth',
        'scroll_animation_duration_ms' => 350,
        'scroll_animation_easing'    => 'ease',
        'scroll_transition_type'     => 'slide-fade',
        'image_border_radius'        => 8,
        'video_border_radius'        => 8,
        'transition_fade_enabled'    => true,
        'video_thumbnail_width'      => 60,
        'video_thumbnail_height'     => 45,
        'image_thumbnail_width'      => 60,
        'image_thumbnail_height'     => 60,
        'thumbnail_gap'              => 6,
        'thumbnail_wheel_scroll_enabled' => true,
        'thumbnail_drag_scroll_enabled'  => true,
        'thumbnail_scroll_buttons_visible' => false,
        'nav_arrow_position'         => 'center',
        'nav_arrow_size'             => 36,
        'nav_arrow_color'            => '#ffffff',
        'nav_arrow_bg_color'         => 'rgba(0,0,0,0.45)',
        'nav_arrow_border_width'     => 0,
        'nav_arrow_hover_scale'      => 1.1,
        'nav_arrow_auto_hide_ms'     => 0,
        'dot_nav_enabled'            => true,
        'dot_nav_position'           => 'below',
        'dot_nav_size'               => 10,
        'dot_nav_active_color'       => 'var(--wpsg-color-primary)',
        'dot_nav_inactive_color'     => 'rgba(128,128,128,0.4)',
        'dot_nav_shape'              => 'circle',
        'dot_nav_spacing'            => 6,
        'dot_nav_active_scale'       => 1.3,
        'image_shadow_preset'        => 'subtle',
        'video_shadow_preset'        => 'subtle',
        'image_shadow_custom'        => '0 2px 8px rgba(0,0,0,0.15)',
        'video_shadow_custom'        => '0 2px 8px rgba(0,0,0,0.15)',
        'grid_card_width'            => 160,
        'grid_card_aspect_ratio'     => 'auto',
        'grid_card_max_columns'      => 0,
        'grid_card_min_height'       => 0,
        'grid_card_height'           => 224,
        'mosaic_target_row_height'   => 200,
        // P51-E: Spotlight / Hero adapter nested settings. These are persisted
        // only inside gallery_config.adapterSettings, but must exist here so the
        // nested sanitizer's array_key_exists($defaults) gate accepts them
        // (same pattern as tile_size below). Without these the values are
        // silently dropped on save for both global config and campaign overrides.
        'spotlight_hero_aspect_ratio'   => '16:9',
        'spotlight_thumbnail_size'      => 80,
        'spotlight_thumbnail_size_unit' => 'px',
        'spotlight_transition_duration' => 250,
        'spotlight_strip_position'      => 'below',
        'spotlight_hero_max_width'      => 0,
        'spotlight_hero_max_width_unit' => 'px',
        'spotlight_hero_justification'  => 'center',
        // P51-E: Vertical Scroll Snap adapter nested settings.
        'scroll_snap_alignment'         => 'start',
        'scroll_snap_page_indicator'    => true,
        'scroll_snap_max_width'         => 0,
        'scroll_snap_max_width_unit'    => 'px',
        // P51-E: Masonry entrance animation nested settings.
        'masonry_entrance_animation'    => 'none',
        'masonry_entrance_stagger'      => 60,
        'tile_size'                  => 150,
        'tile_gap_x'                 => 8,
        'tile_gap_y'                 => 8,
        'tile_border_width'          => 0,
        'tile_border_color'          => '#ffffff',
        'tile_glow_enabled'          => false,
        'tile_glow_color'            => '#7c9ef8',
        'tile_glow_spread'           => 12,
        'tile_hover_bounce'          => true,
        'masonry_columns'            => 0,
        'image_bg_type'              => 'none',
        'image_bg_color'             => '#1a1a2e',
        'image_bg_gradient'          => 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)',
        'image_bg_image_url'         => '',
        'video_bg_type'              => 'none',
        'video_bg_color'             => '#0d0d0d',
        'video_bg_gradient'          => 'linear-gradient(135deg, #0d0d0d 0%, #1a1a2e 100%)',
        'video_bg_image_url'         => '',
        'unified_bg_type'            => 'none',
        'unified_bg_color'           => '#1a1a2e',
        'unified_bg_gradient'        => 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)',
        'unified_bg_image_url'       => '',
        'card_border_radius'         => 8,
        'card_border_width'          => 4,
        'card_border_mode'           => 'auto',
        'card_border_color'          => '#228be6',
        'card_shadow_preset'         => 'subtle',
        'card_thumbnail_height'      => 200,
        'card_thumbnail_fit'         => 'cover',
        'card_grid_columns'          => 0,
        'card_gap_h'                 => 16,
        'card_gap_v'                 => 16,
        'card_max_width'             => 0,
        'modal_cover_height'         => 240,
        'modal_transition'           => 'pop',
        'modal_transition_duration'  => 300,
        'modal_max_height'           => 90,
        'card_display_mode'          => 'load-more',
        'card_rows_per_page'         => 3,
        'card_page_dot_nav'          => false,
        'card_page_transition_ms'    => 300,
        'show_gallery_title'         => true,
        'show_gallery_subtitle'      => true,
        'show_access_mode'           => true,
        'show_filter_tabs'           => true,
        'show_search_box'            => true,
        'app_max_width'              => 1200,
        'app_padding'                => 16,
        'settings_panel_width'       => 600,
        'settings_panel_animation'   => 'slide-left',
        'admin_panel_max_width'      => 0,
        'wp_full_bleed_desktop'      => false,
        'wp_full_bleed_tablet'       => false,
        'wp_full_bleed_mobile'       => false,
        'image_tile_size'            => 150,
        'video_tile_size'            => 150,
        'cache_ttl'                  => 3600,
        'thumbnail_cache_ttl'        => 86400,
        'optimize_on_upload'         => false,
        'optimize_max_width'         => 1920,
        'optimize_max_height'        => 1920,
        'optimize_quality'           => 82,
        'optimize_webp_enabled'      => false,
        'advanced_settings_enabled'  => false,
        'card_locked_opacity'            => 0.5,
        'card_gradient_start_opacity'    => 0.0,
        'card_gradient_end_opacity'      => 0.85,
        'card_lock_icon_size'            => 32,
        'card_access_icon_size'          => 14,
        'card_badge_offset_y'            => 8,
        'card_company_badge_max_width'   => 160,
        'card_thumbnail_hover_transition_ms' => 300,
        'gallery_title_text'             => 'Gallery',
        'gallery_subtitle_text'          => '',
        'campaign_about_heading_text'    => 'About',
        'modal_cover_mobile_ratio'       => 0.6,
        'modal_cover_tablet_ratio'       => 0.75,
        'modal_close_button_size'        => 36,
        'modal_close_button_bg_color'    => 'rgba(0,0,0,0.5)',
        'modal_content_max_width'        => 900,
        'campaign_description_line_height' => 1.6,
        'modal_mobile_breakpoint'        => 768,
        'card_page_transition_opacity'   => 0.3,
        'upload_max_size_mb'             => 50,
        'max_batch_upload_size'          => 20,
        'upload_allowed_types'           => 'image/*,video/*',
        'library_page_size'              => 20,
        'media_list_page_size'           => 50,
        'media_compact_card_height'      => 100,
        'media_small_card_height'        => 80,
        'media_medium_card_height'       => 240,
        'media_large_card_height'        => 340,
        'media_list_min_width'           => 600,
        'swr_deduping_interval_ms'       => 5000,
        'notification_dismiss_ms'        => 4000,
        'tile_hover_overlay_opacity'     => 0.6,
        'tile_bounce_scale_hover'        => 1.08,
        'tile_bounce_scale_active'       => 1.02,
        'tile_bounce_duration_ms'        => 300,
        'tile_base_transition_duration_ms' => 250,
        'hex_vertical_overlap_ratio'     => 0.25,
        'diamond_vertical_overlap_ratio' => 0.45,
        'hex_clip_path'                  => 'polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)',
        'diamond_clip_path'              => 'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)',
        'tile_default_per_row'           => 5,
        'photo_normalize_height'         => 300,
        'masonry_auto_column_breakpoints' => '480:2,768:3,1024:4,1280:5',
        'grid_card_hover_shadow'         => '0 4px 12px rgba(0,0,0,0.3)',
        'grid_card_default_shadow'       => '0 2px 8px rgba(0,0,0,0.15)',
        'grid_card_hover_scale'          => 1.02,
        'tile_transition_duration_ms'    => 200,
        'lightbox_transition_ms'         => 250,
        'lightbox_backdrop_color'        => 'rgba(0,0,0,0.92)',
        'lightbox_entry_scale'           => 0.92,
        'lightbox_video_max_width'       => 900,
        'lightbox_video_height'          => 506,
        'lightbox_media_max_height'      => '85vh',
        'lightbox_z_index'               => 1000,
        'dot_nav_max_visible_dots'       => 7,
        'nav_arrow_edge_inset'           => 8,
        'nav_arrow_min_hit_target'       => 44,
        'nav_arrow_fade_duration_ms'     => 200,
        'nav_arrow_scale_transition_ms'  => 150,
        'viewport_height_mobile_ratio'   => 0.65,
        'viewport_height_tablet_ratio'   => 0.8,
        'search_input_min_width'         => 200,
        'search_input_max_width'         => 280,
        'expiry_warning_threshold_ms'    => 300000,
        'admin_search_debounce_ms'       => 300,
        'login_min_password_length'      => 1,
        'login_form_max_width'           => 400,
        'auth_bar_backdrop_blur'         => 8,
        'auth_bar_mobile_breakpoint'     => 768,
        'card_auto_columns_breakpoints'  => '480:1,768:2,1024:3,1280:4',
        // P56-B: Configurable breakpoint thresholds for the classic carousel adapter.
        'mobile_breakpoint_px'           => 768,
        'tablet_breakpoint_px'           => 1200,
        'session_idle_timeout_minutes' => 0,
        'layout_builder_scope'           => 'full',
        'preserve_data_on_uninstall'     => true,
        'archive_purge_days'             => 0,
        'archive_purge_grace_days'       => 30,
        'analytics_retention_days'       => 0,
        // P72-F: opt-in PII retention windows. 0 = never purge (default).
        'access_requests_retention_days' => 0,
        'audit_log_retention_days'       => 0,
        'magic_link_landing_page_id'     => 0,
        'enable_analytics'               => false,
        'default_visibility'             => 'public',
        'show_card_company_name'         => true,
        'show_card_media_counts'         => true,
        'show_card_title'                => true,
        'show_card_description'          => true,
        'show_card_border'               => true,
        'show_card_access_badge'         => true,
        'show_card_thumbnail_fade'       => true,
        'viewer_bg_type'                 => 'theme',
        'viewer_bg_color'                => '',
        'viewer_bg_gradient'             => [],
        'show_viewer_border'             => true,
        'card_max_columns'               => 0,
        'card_aspect_ratio'              => 'auto',
        'card_min_height'                => 0,
        'campaign_modal_fullscreen'      => false,
        'show_campaign_company_name'     => true,
        'show_campaign_date'             => true,
        'show_campaign_about'            => true,
        'show_campaign_description'      => true,
        'show_campaign_stats'            => true,
        'campaign_stats_admin_only'      => true,
        'campaign_open_mode'             => 'full',
        'auth_bar_display_mode'          => 'floating',
        'auth_bar_drag_margin'           => 16,
        'show_settings_tooltips'         => true,
        'typography_overrides'           => '{}',
        'show_in_context_editors'        => true,
        'show_card_info_panel'           => true,
        'show_campaign_cover_image'      => true,
        'show_campaign_tags'             => true,
        'show_campaign_admin_actions'    => true,
        'show_campaign_gallery_labels'   => true,
        'fullscreen_content_max_width'   => 0,
        'modal_max_width'                => 1200,
        'modal_bg_type'                  => 'theme',
        'modal_bg_color'                 => '',
        'modal_bg_gradient'              => '{}',
        'gallery_image_label'            => 'Images',
        'gallery_video_label'            => 'Videos',
        'gallery_label_justification'    => 'left',
        'show_gallery_label_icon'        => false,
        'modal_gallery_max_width'        => 0,
        'modal_gallery_gap'              => 32,
        'modal_gallery_margin'           => 0,
        'modal_gallery_vertical_align'   => 'start',
        'modal_gallery_offset_y'         => 0,
        'gallery_sizing_mode'            => 'auto',
        'gallery_manual_height'          => '420px',
        'gallery_section_max_width'      => 0,
        'gallery_section_max_height'     => 0,
        'gallery_section_height_mode'    => 'auto',
        'gallery_section_min_width'      => 300,
        'gallery_section_min_height'     => 150,
        'gallery_section_content_align_x' => 'center',
        'gallery_section_content_align_y' => 'start',
        'gallery_section_content_offset_x' => 0,
        'gallery_section_content_offset_y' => 0,
        'section_scale'                  => 1,
        'per_type_section_equal_height'  => false,
        'modal_inner_padding'            => 16,
        'gallery_section_padding'        => 16,
        'adapter_content_padding'        => 0,
        'adapter_sizing_mode'            => 'fill',
        'adapter_max_width_pct'          => 100,
        'adapter_max_height_pct'         => 100,
        'card_max_width_unit'            => 'px',
        'card_justify_content'           => 'center',
        'card_scale'                     => 1.0,
        'card_gallery_vertical_align'    => 'start',
        'card_gallery_min_height'        => 0,
        'card_gallery_max_height'        => 0,
        'card_gallery_offset_x'          => 0,
        'card_gallery_offset_y'          => 0,
        'adapter_item_gap'               => 16,
        'adapter_justify_content'        => 'center',
        'item_scale'                     => 1,
        'modal_content_vertical_align'   => 'top',
        'carousel_visible_cards'         => 1,
        'carousel_autoplay'              => false,
        'carousel_autoplay_speed'        => 3000,
        'carousel_autoplay_pause_on_hover' => true,
        'carousel_autoplay_direction'    => 'ltr',
        'carousel_drag_enabled'          => true,
        'carousel_darken_unfocused'      => false,
        'carousel_darken_opacity'        => 0.5,
        'carousel_edge_fade'             => false,
        'carousel_loop'                  => true,
        'carousel_gap'                   => 16,
        'settings_drawer_blur_enabled'   => true,
        // P25-X: CSS unit companion fields (all default to 'px')
        'app_max_width_unit'             => 'px',
        'app_padding_unit'               => 'px',
        'settings_panel_width_unit'      => 'px',
        'admin_panel_max_width_unit'     => 'px',
        'card_gap_h_unit'                => 'px',
        'card_gap_v_unit'                => 'px',
        'card_thumbnail_height_unit'     => 'px',
        'card_min_height_unit'           => 'px',
        'card_border_radius_unit'        => 'px',
        'card_gallery_min_height_unit'   => 'px',
        'card_gallery_max_height_unit'   => 'px',
        'card_gallery_offset_x_unit'     => 'px',
        'card_gallery_offset_y_unit'     => 'px',
        'modal_max_width_unit'           => 'px',
        'modal_content_max_width_unit'   => 'px',
        'modal_gallery_max_width_unit'   => 'px',
        'modal_inner_padding_unit'       => 'px',
        'modal_cover_height_unit'        => 'px',
        'modal_gallery_gap_unit'         => 'px',
        'modal_gallery_margin_unit'      => 'px',
        'modal_gallery_offset_y_unit'    => 'px',
        'fullscreen_content_max_width_unit' => 'px',
        'lightbox_video_max_width_unit'  => 'px',
        'lightbox_video_height_unit'     => 'px',
        'gallery_section_padding_unit'   => 'px',
        'gallery_section_content_offset_x_unit' => 'px',
        'gallery_section_content_offset_y_unit' => 'px',
        // P25-X: Common/adapter nested unit defaults
        'gallery_section_max_width_unit' => 'px',
        'gallery_section_max_height_unit' => 'px',
        'gallery_section_min_width_unit' => 'px',
        'gallery_section_min_height_unit' => 'px',
        'adapter_content_padding_unit'   => 'px',
        'adapter_item_gap_unit'          => 'px',
        'video_viewport_height_unit'     => 'px',
        'image_viewport_height_unit'     => 'px',
        'image_border_radius_unit'       => 'px',
        'video_border_radius_unit'       => 'px',
        'carousel_gap_unit'              => 'px',
        'tile_size_unit'                 => 'px',
        'image_tile_size_unit'           => 'px',
        'video_tile_size_unit'           => 'px',
        'tile_gap_x_unit'               => 'px',
        'tile_gap_y_unit'               => 'px',
        'grid_card_width_unit'           => 'px',
        'grid_card_height_unit'          => 'px',
        'mosaic_target_row_height_unit'  => 'px',
        'photo_normalize_height_unit'    => 'px',
        // P35-B: Campaign listing adapter selection (gallery-level, not adapter-specific)
        'campaign_listing_adapter_id'        => 'compact-grid',
        'campaign_listing_adapter_id_mobile' => '',
        'campaign_listing_adapter_id_tablet' => '',
        // P37-LB: Layout template used when campaign_listing_adapter_id is 'layout-builder'
        'campaign_listing_layout_template_id' => '',
        // P48-D: Per-space authenticated rate-limit quota (requests per minute). 0 = use global filter default.
        'rate_limit_requests_per_minute'      => 0,
    ];

    /**
     * Settings that are admin-only.
     *
     * @var string[]
     */
    private static $admin_only_fields = [
        'auth_provider',
        'api_base',
        'allow_user_theme_override',
        'debug_component_markers',
        'cache_ttl',
        'thumbnail_cache_ttl',
        'optimize_on_upload',
        'optimize_max_width',
        'optimize_max_height',
        'optimize_quality',
        'optimize_webp_enabled',
        'advanced_settings_enabled',
        'upload_max_size_mb',
        'max_batch_upload_size',
        'upload_allowed_types',
        'swr_deduping_interval_ms',
        'notification_dismiss_ms',
        'expiry_warning_threshold_ms',
        'admin_search_debounce_ms',
        'login_min_password_length',
        'login_form_max_width',
        'auth_bar_backdrop_blur',
        'auth_bar_mobile_breakpoint',
        'session_idle_timeout_minutes',
        'preserve_data_on_uninstall',
        'archive_purge_days',
        'archive_purge_grace_days',
        'analytics_retention_days',
        'access_requests_retention_days',
        'audit_log_retention_days',
        'magic_link_landing_page_id',
    ];

    /**
     * Settings that space owners may override (subset of non-admin-only fields).
     *
     * @var string[]
     */
    private static $space_overridable_fields = [
        // ── Core display ─────────────────────────────────────────────────────
        'theme',
        'gallery_layout',
        'items_per_page',
        'enable_lightbox',
        'enable_animations',
        'wp_full_bleed_desktop',
        'wp_full_bleed_tablet',
        'wp_full_bleed_mobile',
        'typography_overrides',
        // ── Gallery text / labels ─────────────────────────────────────────────
        'gallery_title_text',
        'gallery_subtitle_text',
        'show_gallery_title',
        'show_gallery_subtitle',
        // ── Card + campaign UI toggles ────────────────────────────────────────
        'show_access_mode',
        'show_filter_tabs',
        'show_search_box',
        'show_card_company_name',
        'show_card_media_counts',
        'show_card_title',
        'show_card_description',
        'show_card_border',
        'show_card_access_badge',
        'show_card_thumbnail_fade',
        'show_card_info_panel',
        'show_campaign_company_name',
        'show_campaign_date',
        'show_campaign_about',
        'show_campaign_description',
        'show_campaign_stats',
        'default_visibility',
        // ── Campaign listing ──────────────────────────────────────────────────
        'campaign_listing_adapter_id',
        'campaign_listing_adapter_id_mobile',
        'campaign_listing_adapter_id_tablet',
        'campaign_listing_layout_template_id',
        // ── P47-M: Branding text & labels ─────────────────────────────────────
        'campaign_about_heading_text',
        'gallery_image_label',
        'gallery_video_label',
        'gallery_label_justification',
        'show_gallery_label_icon',
        // ── P47-M: Backgrounds ────────────────────────────────────────────────
        'image_bg_type',
        'image_bg_color',
        'image_bg_gradient',
        'image_bg_image_url',
        'video_bg_type',
        'video_bg_color',
        'video_bg_gradient',
        'video_bg_image_url',
        'unified_bg_type',
        'unified_bg_color',
        'unified_bg_gradient',
        'unified_bg_image_url',
        'viewer_bg_type',
        'viewer_bg_color',
        'viewer_bg_gradient',
        'modal_bg_type',
        'modal_bg_color',
        'modal_bg_gradient',
        // ── P47-M: Nav arrows + dot nav ───────────────────────────────────────
        'nav_arrow_position',
        'nav_arrow_size',
        'nav_arrow_color',
        'nav_arrow_bg_color',
        'dot_nav_enabled',
        'dot_nav_position',
        'dot_nav_size',
        'dot_nav_active_color',
        'dot_nav_inactive_color',
        'dot_nav_shape',
        // ── P47-M: Shadows & borders ──────────────────────────────────────────
        'image_shadow_preset',
        'video_shadow_preset',
        'card_shadow_preset',
        'card_border_radius',
        'card_border_width',
        'card_border_color',
        'tile_border_width',
        'tile_border_color',
        // ── P47-M: Display toggles ────────────────────────────────────────────
        'show_viewer_border',
        'show_campaign_cover_image',
        'show_campaign_tags',
        'show_campaign_gallery_labels',
        'transition_fade_enabled',
        'campaign_open_mode',
        // ── P47-M parity fix: card_border_radius was promoted without its unit ──
        'card_border_radius_unit',
        // ── P47-N: Card layout & styling ──────────────────────────────────────
        'card_thumbnail_height', 'card_thumbnail_height_unit',
        'card_thumbnail_fit',
        'card_gap_h', 'card_gap_h_unit',
        'card_gap_v', 'card_gap_v_unit',
        'card_max_width', 'card_max_width_unit',
        'card_min_height', 'card_min_height_unit',
        'card_aspect_ratio',
        'card_grid_columns',
        'card_max_columns',
        'card_scale',
        'card_justify_content',
        'card_display_mode',
        'card_rows_per_page',
        'card_gradient_start_opacity',
        'card_gradient_end_opacity',
        'card_border_mode',
        'card_gallery_vertical_align',
        'card_gallery_min_height', 'card_gallery_min_height_unit',
        'card_gallery_max_height', 'card_gallery_max_height_unit',
        'card_gallery_offset_x', 'card_gallery_offset_x_unit',
        'card_gallery_offset_y', 'card_gallery_offset_y_unit',
        'grid_card_width', 'grid_card_width_unit',
        'grid_card_height', 'grid_card_height_unit',
        'grid_card_aspect_ratio',
        'grid_card_max_columns',
        'grid_card_min_height',
        'image_shadow_custom',
        'video_shadow_custom',
        // ── P47-N: Tile / mosaic / hex / diamond ──────────────────────────────
        'tile_size', 'tile_size_unit',
        'tile_gap_x', 'tile_gap_x_unit',
        'tile_gap_y', 'tile_gap_y_unit',
        'tile_default_per_row',
        'image_tile_size', 'image_tile_size_unit',
        'video_tile_size', 'video_tile_size_unit',
        'masonry_columns',
        'mosaic_target_row_height', 'mosaic_target_row_height_unit',
        'photo_normalize_height', 'photo_normalize_height_unit',
        'hex_vertical_overlap_ratio',
        'diamond_vertical_overlap_ratio',
        // ── P47-N: Carousel ────────────────────────────────────────────────────
        'carousel_visible_cards',
        'carousel_autoplay',
        'carousel_autoplay_speed',
        'carousel_autoplay_pause_on_hover',
        'carousel_autoplay_direction',
        'carousel_drag_enabled',
        'carousel_darken_unfocused',
        'carousel_darken_opacity',
        'carousel_edge_fade',
        'carousel_loop',
        'carousel_gap', 'carousel_gap_unit',
        // ── P47-N: Modal & lightbox ────────────────────────────────────────────
        'modal_cover_height', 'modal_cover_height_unit',
        'modal_cover_mobile_ratio',
        'modal_cover_tablet_ratio',
        'modal_transition',
        'modal_transition_duration',
        'modal_max_width', 'modal_max_width_unit',
        'modal_max_height',
        'modal_gallery_max_width', 'modal_gallery_max_width_unit',
        'modal_gallery_gap', 'modal_gallery_gap_unit',
        'modal_gallery_margin', 'modal_gallery_margin_unit',
        'modal_gallery_vertical_align',
        'modal_gallery_offset_y', 'modal_gallery_offset_y_unit',
        'modal_close_button_size',
        'modal_inner_padding', 'modal_inner_padding_unit',
        'modal_content_max_width', 'modal_content_max_width_unit',
        'modal_content_vertical_align',
        'campaign_modal_fullscreen',
        'fullscreen_content_max_width', 'fullscreen_content_max_width_unit',
        'lightbox_transition_ms',
        'lightbox_backdrop_color',
        'lightbox_entry_scale',
        'lightbox_video_max_width', 'lightbox_video_max_width_unit',
        'lightbox_video_height', 'lightbox_video_height_unit',
        // ── P47-N: Gallery section / adapter layout ────────────────────────────
        'gallery_sizing_mode',
        'gallery_manual_height',
        'gallery_section_padding', 'gallery_section_padding_unit',
        'gallery_section_max_width', 'gallery_section_max_width_unit',
        'gallery_section_max_height', 'gallery_section_max_height_unit',
        'gallery_section_min_width', 'gallery_section_min_width_unit',
        'gallery_section_min_height', 'gallery_section_min_height_unit',
        'gallery_section_height_mode',
        'gallery_section_content_align_x',
        'gallery_section_content_align_y',
        'gallery_section_content_offset_x', 'gallery_section_content_offset_x_unit',
        'gallery_section_content_offset_y', 'gallery_section_content_offset_y_unit',
        'section_scale',
        'per_type_section_equal_height',
        'app_max_width', 'app_max_width_unit',
        'app_padding', 'app_padding_unit',
        'adapter_sizing_mode',
        'adapter_max_width_pct',
        'adapter_max_height_pct',
        'adapter_item_gap', 'adapter_item_gap_unit',
        'adapter_justify_content',
        'adapter_content_padding', 'adapter_content_padding_unit',
        'item_scale',
        // ── P47-N: Viewport & responsive ──────────────────────────────────────
        'video_viewport_height', 'video_viewport_height_unit',
        'image_viewport_height', 'image_viewport_height_unit',
        'viewport_height_tablet_ratio',
        'viewport_height_mobile_ratio',
        'modal_mobile_breakpoint',
        // ── P48-D: Per-space rate limiting ────────────────────────────────────
        'rate_limit_requests_per_minute',
    ];

    /**
     * Valid options for select fields.
     *
     * @var array
     */
    private static $valid_options = [
        'auth_provider'       => ['wp-jwt', 'none'],
        'default_visibility'  => ['public', 'private'],
        'theme'          => [
            'default-dark',
            'default-light',
            'material-dark',
            'material-light',
            'darcula',
            'nord',
            'solarized-dark',
            'solarized-light',
            'high-contrast',
            'catppuccin-mocha',
            'tokyo-night',
            'gruvbox-dark',
            'cyberpunk',
            'synthwave',
            'github-light',
            'catppuccin-latte',
            'sunset-boulevard',
            'ocean-breeze',
            'crimson-canvas',
            'forest-whisper',
            'halloween',
            'reverse-halloween',
            'midnight-rose',
        ],
        'gallery_layout' => ['grid', 'masonry', 'carousel'],
        'scroll_animation_style' => ['smooth', 'instant'],
        'scroll_animation_easing' => ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'],
        'scroll_transition_type' => ['fade', 'slide', 'slide-fade'],
        'nav_arrow_position'     => ['top', 'center', 'bottom'],
        'dot_nav_position'       => ['below', 'overlay-bottom', 'overlay-top'],
        // P51-E: Spotlight / Scroll-snap / Masonry-entrance nested enum + unit options.
        'spotlight_hero_aspect_ratio'   => ['16:9', '4:3', '3:2', '1:1', '3:4'],
        'spotlight_thumbnail_size_unit' => ['px', '%', 'vw', 'em', 'rem'],
        'spotlight_strip_position'      => ['below', 'right'],
        'spotlight_hero_max_width_unit' => ['px', '%', 'vw', 'em', 'rem'],
        'spotlight_hero_justification'  => ['start', 'center', 'end'],
        'scroll_snap_alignment'         => ['start', 'center', 'end'],
        'scroll_snap_max_width_unit'    => ['px', '%', 'vw', 'em', 'rem'],
        'masonry_entrance_animation'    => ['none', 'waterfall'],
        'dot_nav_shape'          => ['circle', 'pill', 'square'],
        'image_shadow_preset'    => ['none', 'subtle', 'medium', 'strong', 'custom'],
        'video_shadow_preset'    => ['none', 'subtle', 'medium', 'strong', 'custom'],
        'card_shadow_preset'     => ['none', 'subtle', 'medium', 'dramatic'],
        'card_thumbnail_fit'     => ['cover', 'contain'],
        'card_border_mode'       => ['auto', 'single', 'individual'],
        'modal_transition'       => ['pop', 'fade', 'slide-up'],
        'card_display_mode'      => ['show-all', 'load-more', 'paginated'],
        'image_bg_type'          => ['none', 'solid', 'gradient', 'image'],
        'video_bg_type'          => ['none', 'solid', 'gradient', 'image'],
        'unified_bg_type'        => ['none', 'solid', 'gradient', 'image'],
        'layout_builder_scope'       => ['full', 'viewport'],
        'viewer_bg_type'             => ['theme', 'transparent', 'solid', 'gradient'],
        'modal_bg_type'              => ['theme', 'transparent', 'solid', 'gradient'],
        'grid_card_aspect_ratio'     => ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9', '5:7'],
        'card_aspect_ratio'          => ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9'],
        'gallery_label_justification' => ['left', 'center', 'right'],
        'campaign_open_mode'          => ['full', 'galleries-only'],
        'auth_bar_display_mode'       => ['bar', 'floating', 'draggable', 'minimal', 'auto-hide'],
        'gallery_sizing_mode'         => ['auto', 'viewport', 'manual'],
        'gallery_section_height_mode' => ['auto', 'manual', 'viewport'],
        'adapter_sizing_mode'         => ['fill', 'manual'],
        'card_max_width_unit'         => ['px', '%', 'vw', 'em', 'rem'],
        'card_justify_content'        => ['start', 'center', 'end', 'space-between', 'space-evenly'],
        'card_gallery_vertical_align' => ['start', 'center', 'end'],
        'adapter_justify_content'     => ['start', 'center', 'end', 'space-between', 'space-evenly', 'stretch'],
        'modal_content_vertical_align' => ['top', 'center', 'bottom'],
        'modal_gallery_vertical_align' => ['start', 'center', 'end'],
        'gallery_section_content_align_x' => ['start', 'center', 'end'],
        'gallery_section_content_align_y' => ['start', 'center', 'end'],
        'carousel_autoplay_direction'  => ['ltr', 'rtl'],
        // P57-A: Settings panel open/close animation variants
        'settings_panel_animation'     => ['slide-left', 'fade', 'scale', 'none'],
        // P25-X: CSS unit valid options
        'app_max_width_unit'             => ['px', '%', 'vw', 'em', 'rem'],
        'app_padding_unit'               => ['px', 'em', 'rem', '%'],
        'settings_panel_width_unit'      => ['px', '%', 'vw', 'em', 'rem'],
        'admin_panel_max_width_unit'     => ['px', '%', 'vw', 'em', 'rem'],
        'card_gap_h_unit'                => ['px', 'em', 'rem', '%'],
        'card_gap_v_unit'                => ['px', 'em', 'rem', '%'],
        'card_thumbnail_height_unit'     => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'card_min_height_unit'           => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'card_border_radius_unit'        => ['px', '%', 'em', 'rem'],
        'card_gallery_min_height_unit'   => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'card_gallery_max_height_unit'   => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'card_gallery_offset_x_unit'     => ['px', 'em', 'rem', '%', 'vw', 'vh'],
        'card_gallery_offset_y_unit'     => ['px', 'em', 'rem', '%', 'vw', 'vh'],
        'modal_max_width_unit'           => ['px', '%', 'vw', 'em', 'rem'],
        'modal_content_max_width_unit'   => ['px', '%', 'vw', 'em', 'rem'],
        'modal_gallery_max_width_unit'   => ['px', '%', 'vw', 'em', 'rem'],
        'modal_inner_padding_unit'       => ['px', 'em', 'rem', '%'],
        'modal_cover_height_unit'        => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'modal_gallery_gap_unit'         => ['px', 'em', 'rem', '%'],
        'modal_gallery_margin_unit'      => ['px', 'em', 'rem', '%'],
        'modal_gallery_offset_y_unit'    => ['px', 'em', 'rem', '%', 'vw', 'vh'],
        'fullscreen_content_max_width_unit' => ['px', '%', 'vw', 'em', 'rem'],
        'lightbox_video_max_width_unit'  => ['px', '%', 'vw', 'em', 'rem'],
        'lightbox_video_height_unit'     => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'gallery_section_padding_unit'   => ['px', 'em', 'rem', '%'],
        'gallery_section_content_offset_x_unit' => ['px', 'em', 'rem', '%', 'vw', 'vh'],
        'gallery_section_content_offset_y_unit' => ['px', 'em', 'rem', '%', 'vw', 'vh'],
        'gallery_section_max_width_unit' => ['px', '%', 'vw', 'em', 'rem'],
        'gallery_section_max_height_unit' => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'gallery_section_min_width_unit' => ['px', '%', 'vw', 'em', 'rem'],
        'gallery_section_min_height_unit' => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'adapter_content_padding_unit'   => ['px', 'em', 'rem', '%'],
        'adapter_item_gap_unit'          => ['px', 'em', 'rem', '%'],
        'video_viewport_height_unit'     => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'image_viewport_height_unit'     => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'image_border_radius_unit'       => ['px', '%', 'em', 'rem'],
        'video_border_radius_unit'       => ['px', '%', 'em', 'rem'],
        'carousel_gap_unit'              => ['px', 'em', 'rem', '%'],
        'tile_size_unit'                 => ['px', '%', 'vw', 'em', 'rem'],
        'image_tile_size_unit'           => ['px', '%', 'vw', 'em', 'rem'],
        'video_tile_size_unit'           => ['px', '%', 'vw', 'em', 'rem'],
        'tile_gap_x_unit'               => ['px', 'em', 'rem', '%'],
        'tile_gap_y_unit'               => ['px', 'em', 'rem', '%'],
        'grid_card_width_unit'           => ['px', '%', 'vw', 'em', 'rem'],
        'grid_card_height_unit'          => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'mosaic_target_row_height_unit'  => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        'photo_normalize_height_unit'    => ['px', '%', 'vh', 'dvh', 'svh', 'lvh', 'em', 'rem'],
        // P35-B: Campaign listing adapter ID values ('' = inherit desktop value on mobile/tablet)
        // 'classic' is the canonical id; 'carousel' is kept as a back-compat alias.
        // P37-LB: 'layout-builder' added as a listing-compatible adapter.
        'campaign_listing_adapter_id'        => ['classic', 'compact-grid', 'masonry', 'justified', 'carousel', 'layout-builder'],
        'campaign_listing_adapter_id_mobile' => ['', 'classic', 'compact-grid', 'masonry', 'justified', 'carousel', 'layout-builder'],
        'campaign_listing_adapter_id_tablet' => ['', 'classic', 'compact-grid', 'masonry', 'justified', 'carousel', 'layout-builder'],
    ];

    /**
     * Numeric ranges for settings.
     *
     * @var array<string, array{0: int|float, 1: int|float}>
     */
    private static $field_ranges = [
        'items_per_page'              => [1, 100],
        'video_viewport_height'       => [180, 900],
        'image_viewport_height'       => [180, 900],
        'thumbnail_scroll_speed'      => [0.25, 3],
        'scroll_animation_duration_ms' => [0, 2000],
        'image_border_radius'         => [0, 48],
        'video_border_radius'         => [0, 48],
        'video_thumbnail_width'       => [30, 200],
        'video_thumbnail_height'      => [30, 200],
        'image_thumbnail_width'       => [30, 200],
        'image_thumbnail_height'      => [30, 200],
        'thumbnail_gap'               => [0, 24],
        'nav_arrow_size'              => [20, 64],
        'nav_arrow_border_width'      => [0, 6],
        'nav_arrow_hover_scale'       => [1.0, 1.5],
        'nav_arrow_auto_hide_ms'      => [0, 10000],
        'dot_nav_size'                => [4, 24],
        'dot_nav_spacing'             => [2, 20],
        'dot_nav_active_scale'        => [1.0, 2.0],
        'mosaic_target_row_height'    => [60, 600],
        // P51-E: Spotlight / Scroll-snap / Masonry-entrance nested numeric ranges.
        'spotlight_thumbnail_size'    => [0, 600],
        'spotlight_transition_duration' => [0, 1000],
        'spotlight_hero_max_width'    => [0, 1800],
        'scroll_snap_max_width'       => [0, 1800],
        'masonry_entrance_stagger'    => [0, 300],
        'grid_card_width'             => [80, 400],
        'grid_card_max_columns'       => [0, 8],
        'grid_card_min_height'        => [0, 600],
        'grid_card_height'            => [80, 600],
        'tile_size'                   => [60, 400],
        'tile_gap_x'                  => [0, 60],
        'tile_gap_y'                  => [0, 60],
        'tile_border_width'           => [0, 20],
        'tile_glow_spread'            => [2, 60],
        'masonry_columns'             => [0, 8],
        'card_border_radius'          => [0, 24],
        'card_border_width'           => [0, 8],
        'card_thumbnail_height'       => [100, 400],
        'card_grid_columns'           => [0, 6],
        'card_gap_h'                  => [0, 48],
        'card_gap_v'                  => [0, 48],
        'card_gallery_min_height'     => [0, 1200],
        'card_gallery_max_height'     => [0, 2000],
        'card_gallery_offset_x'       => [-200, 200],
        'card_gallery_offset_y'       => [-200, 200],
        'modal_cover_height'          => [100, 400],
        'modal_transition_duration'   => [100, 1000],
        'modal_max_height'            => [50, 100],
        'card_rows_per_page'          => [1, 10],
        'card_page_transition_ms'     => [100, 800],
        'app_max_width'               => [0, 3000],
        'app_padding'                 => [0, 100],
        'settings_panel_width'        => [0, 3000],
        'admin_panel_max_width'       => [0, 3000],
        'image_tile_size'             => [60, 400],
        'video_tile_size'             => [60, 400],
        'cache_ttl'                   => [0, 604800],
        'thumbnail_cache_ttl'         => [0, 604800],
        // P67-A: range moved here from the hand-written sanitize_settings() block
        // so the generic loop clamps it (was the only removed int block missing a range).
        'rate_limit_requests_per_minute' => [0, 6000],
        'optimize_max_width'          => [100, 4096],
        'optimize_max_height'         => [100, 4096],
        'optimize_quality'            => [10, 100],
        'card_locked_opacity'         => [0, 1],
        'card_gradient_start_opacity' => [0, 1],
        'card_gradient_end_opacity'   => [0, 1],
        'card_lock_icon_size'         => [12, 64],
        'card_access_icon_size'       => [8, 32],
        'card_badge_offset_y'         => [0, 32],
        'card_company_badge_max_width' => [60, 400],
        'card_thumbnail_hover_transition_ms' => [0, 1000],
        'modal_cover_mobile_ratio'    => [0.2, 1],
        'modal_cover_tablet_ratio'    => [0.2, 1],
        'modal_close_button_size'     => [20, 64],
        'modal_content_max_width'     => [400, 2000],
        'campaign_description_line_height' => [1.0, 3.0],
        'modal_mobile_breakpoint'     => [320, 1280],
        'card_page_transition_opacity' => [0, 1],
        'upload_max_size_mb'          => [1, 500],
        'max_batch_upload_size'       => [1, 100],
        'library_page_size'           => [5, 100],
        'media_list_page_size'        => [10, 200],
        'media_compact_card_height'   => [40, 300],
        'media_small_card_height'     => [40, 300],
        'media_medium_card_height'    => [100, 600],
        'media_large_card_height'     => [100, 800],
        'media_list_min_width'        => [200, 1200],
        'swr_deduping_interval_ms'    => [0, 60000],
        'notification_dismiss_ms'     => [1000, 30000],
        'tile_hover_overlay_opacity'  => [0, 1],
        'tile_bounce_scale_hover'     => [1.0, 1.5],
        'tile_bounce_scale_active'    => [0.8, 1.2],
        'tile_bounce_duration_ms'     => [0, 1000],
        'tile_base_transition_duration_ms' => [0, 1000],
        'hex_vertical_overlap_ratio'  => [0, 0.5],
        'diamond_vertical_overlap_ratio' => [0, 0.8],
        'tile_default_per_row'        => [1, 12],
        'photo_normalize_height'      => [100, 800],
        'grid_card_hover_scale'       => [1.0, 1.3],
        'tile_transition_duration_ms' => [0, 1000],
        'lightbox_transition_ms'      => [0, 1000],
        'lightbox_entry_scale'        => [0.5, 1.0],
        'lightbox_video_max_width'    => [300, 2000],
        'lightbox_video_height'       => [200, 1200],
        'lightbox_z_index'            => [1, 100000],
        'dot_nav_max_visible_dots'    => [3, 20],
        'nav_arrow_edge_inset'        => [0, 48],
        'nav_arrow_min_hit_target'    => [24, 80],
        'nav_arrow_fade_duration_ms'  => [0, 1000],
        'nav_arrow_scale_transition_ms' => [0, 1000],
        'viewport_height_mobile_ratio' => [0.3, 1.0],
        'viewport_height_tablet_ratio' => [0.3, 1.0],
        'search_input_min_width'      => [100, 600],
        'search_input_max_width'      => [100, 800],
        'expiry_warning_threshold_ms' => [60000, 3600000],
        'admin_search_debounce_ms'    => [50, 2000],
        'login_min_password_length'   => [1, 32],
        'login_form_max_width'        => [200, 800],
        'auth_bar_backdrop_blur'      => [0, 24],
        'auth_bar_mobile_breakpoint'  => [320, 1280],
        'session_idle_timeout_minutes' => [0, 480],
        'archive_purge_days'           => [0, 365],
        'archive_purge_grace_days'     => [7, 90],
        'analytics_retention_days'     => [0, 730],
        'access_requests_retention_days' => [0, 3650],
        'audit_log_retention_days'     => [0, 3650],
        'magic_link_landing_page_id'   => [0, PHP_INT_MAX],
        'card_max_columns'             => [0, 8],
        'card_min_height'              => [0, 600],
        'auth_bar_drag_margin'         => [0, 64],
        'fullscreen_content_max_width' => [0, 3000],
        'modal_max_width'              => [0, 3000],
        'modal_gallery_max_width'      => [0, 3000],
        'modal_gallery_gap'            => [0, 120],
        'modal_gallery_margin'         => [0, 120],
        'modal_gallery_offset_y'       => [-200, 200],
        'gallery_section_max_width'    => [0, 3000],
        'gallery_section_max_height'   => [0, 3000],
        'gallery_section_min_width'    => [0, 1200],
        'gallery_section_min_height'   => [0, 1200],
        'gallery_section_content_offset_x' => [-200, 200],
        'gallery_section_content_offset_y' => [-200, 200],
        'modal_inner_padding'          => [0, 64],
        'gallery_section_padding'      => [0, 60],
        'adapter_content_padding'      => [0, 48],
        'adapter_max_width_pct'        => [50, 100],
        'adapter_max_height_pct'       => [50, 100],
        'adapter_item_gap'             => [0, 64],
        'card_scale'                   => [0.5, 2.0],
        'section_scale'                => [0.5, 2.0],
        'item_scale'                   => [0.5, 2.0],
        'carousel_visible_cards'       => [1, 10],
        'carousel_autoplay_speed'      => [500, 15000],
        'carousel_darken_opacity'      => [0, 1],
        'carousel_gap'                 => [0, 64],
        // P56-B: Configurable breakpoint thresholds.
        'mobile_breakpoint_px'         => [320, 1440],
        'tablet_breakpoint_px'         => [320, 1920],
    ];

    private static function create_default_gallery_scope_config($adapter_id) {
        return [
            'adapterId' => $adapter_id,
        ];
    }

    private static function create_default_gallery_config() {
        return [
            'mode' => 'per-type',
            'breakpoints' => [
                'desktop' => [
                    'unified' => self::create_default_gallery_scope_config('compact-grid'),
                    'image' => self::create_default_gallery_scope_config('classic'),
                    'video' => self::create_default_gallery_scope_config('classic'),
                ],
                'tablet' => [
                    'unified' => self::create_default_gallery_scope_config('compact-grid'),
                    'image' => self::create_default_gallery_scope_config('classic'),
                    'video' => self::create_default_gallery_scope_config('classic'),
                ],
                'mobile' => [
                    'unified' => self::create_default_gallery_scope_config('compact-grid'),
                    'image' => self::create_default_gallery_scope_config('classic'),
                    'video' => self::create_default_gallery_scope_config('classic'),
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public static function get_defaults() {
        $defaults = self::$defaults;

        if (defined('WPSG_DEBUG_COMPONENT_MARKERS')) {
            $defaults['debug_component_markers'] = (bool) WPSG_DEBUG_COMPONENT_MARKERS;
        }

        if (!array_key_exists('gallery_config', $defaults)) {
            $defaults['gallery_config'] = self::create_default_gallery_config();
        }

        if (!array_key_exists('card_config', $defaults)) {
            $defaults['card_config'] = ['breakpoints' => []];
        }

        return $defaults;
    }

    /**
     * @return string[]
     */
    public static function get_admin_only_fields() {
        return self::$admin_only_fields;
    }

    /**
     * @return array
     */
    public static function get_valid_options() {
        return self::$valid_options;
    }

    /**
     * @return array<string, array{0: int|float, 1: int|float}>
     */
    public static function get_field_ranges() {
        return self::$field_ranges;
    }

    /**
     * @return string[]
     */
    public static function get_space_overridable_fields(): array {
        return self::$space_overridable_fields;
    }
}